language: cpp
compiler: gcc
dist: trusty
branches:
  only:
    - master
    - /\d+\.\d+\..+/
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-pip python-numpy python-tk libboost-all-dev libeigen3-dev libqt4-dev libtinyxml-dev pkg-config libyaml-cpp-dev
  - sudo pip install pyyaml scikit-learn scipy cython joblib pandas bs4 matplotlib nose scikit-optimize gym
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - mkdir -p ../build; cd ../build; cp ../bolero/bootstrap_bolero.sh .; ./bootstrap_bolero.sh; rm -rf bolero-dev/learning/bolero/; mv ../bolero bolero-dev/learning; cd bolero-dev; source env.sh; pybob/pybob.py install
  - cd /home/travis/build/rock-learning/build/bolero-dev; source env.sh; cd learning/bolero; nosetests -sv
  - cat /home/travis/build/rock-learning/build/bolero-dev/autoproj/bob/logs/*.txt
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
